### ISSUE TITLE
Add maven support

### ISSUE THREAD

**Issue by mercadanteus** [innc11/QuickShopX#1]
Please add maven support, so server owners can build jar file easily, I thing most server owners are not coders.

**Comment by asforest** [comment]
This is a good idea and I will add Maven support in the next commit.

**Comment by mercadanteus** [comment]
Thanks.

**Comment by mercadanteus** [comment]
To include this english items names file would be very usefull, 
[itemName-en.zip](https://github.com/innc11/QuickShopX/files/4208802/itemName-en.zip)

**Comment by asforest** [comment]
Sorry i just saw this now, thank you for the language file provided, but if you need to use English, you can turn off the "Use custom item names" toggle in the control-panel, it will use Nukkit's built-in language, which is also more beautiful
