### ISSUE TITLE
reverted from english to chinese

### ISSUE THREAD

**Issue by mercadanteus** [innc11/QuickShopX#2]
Hello, I need all this plugin interface and signs to be in english, I accomplished this with the previous version, even succesfuly modified the whole itemName.yml file in this way:
 DIAMOND: "DIAMOND"
  IRON_INGOT: "IRON_INGOT"
  GOLD_INGOT: "GOLD_INGOT" etc

 But with last update, everything revert to chinese, all interface, signs, etc. So I´m using again v 1.4.1.  Can this be solved? thank you very much. Jose Esquivel

**Comment by asforest** [comment]
Yes, of course, maybe i didn't describe the plugin in detail.
In version 1.5.1 you can try to turn off the "useCustomItemNames" option in the control-panel. this will use the name that built in Nukkit(English). If you need to use the "itemName.yml", this is also very easy. just rename the "itemNames.yml" to "item-names.yml", then open this file and modify the "map" at the first line to "mapping" and save, then open the "useCustomItemNames" option again in the control-panel, it will take effect. btw, reloading "item-names.yml" file requires restarting the plugin (/reload command or restart the server)

**Comment by asforest** [comment]
Forgot to say please back up the previous "itemName.yml" before trying to rename it to "item-names.yml". however, I personally recommend using the name built in Nukkit, because it is more pretty.

**Comment by mercadanteus** [comment]
Thank you very much, but after update, not only item names are in chinese, everything is, so i cannot even modify the in-game control panel.  All files on quickshopx folder are still in english, so I don´t know why the plugin behaves this way.
![chino](https://user-images.githubusercontent.com/24380156/75562011-86bf9a80-5a0d-11ea-9870-60628d88025a.png)

**Comment by asforest** [comment]
I'm sorry i didn't see it until now. The plugin's default-language is Chinese.  If you want to use English on 1.5.x, please modify "language: cn" to "language: en" in config.yml. then, type "qs r" in the console. You will see the effect soon

**Comment by mercadanteus** [comment]
That worked, thank you very much.
